<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\PackageAnalyzer.Domain\PackageAnalyzer.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="DeepCloner" Version="0.10.4"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="WoW2.Backbone.General.Exceptions.Catching" Version="8.0.0-alpha.0"/>
        <PackageReference Include="WoW2.Backbone.Language.Core.Time.Provider.Abstractions" Version="8.0.0-alpha.1"/>
        <PackageReference Include="WoW2.Backbone.DataAccess.Relational.EfCore.Repositories.Cached" Version="8.0.0-alpha.4"/>
    </ItemGroup>

</Project>
